version: "3.7"

services:
  mysql:
    container_name: mysql_server
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - project_nodejs
  app_project:
    container_name: NodeJsNativeAPp
    build:
      context: .
      dockerfile: Dockerfile
    image: projectnodejsnative:1.0
    ports:
      - 8000:8000
    depends_on:
      - mysql
    networks:
      - project_nodejs

networks:
  project_nodejs:
    name: project_nodejs

